// canAi/src/app/components/patients/login/login.component.ts
import { HttpClient } from '@angular/common/http';
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { AuthService } from '../../../services/auth.service';
import { UserService } from '../../../services/user.service';
import { Title } from '@angular/platform-browser';

// Google Oauth
import { SocialAuthService, GoogleLoginProvider, SocialUser } from 'angularx-social-login';

declare const google: any;

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrl: '../../../../assets/css/login.css'
})

export class LoginComponent implements OnInit { 

  email: string = '';
  password: string = '';
  errorMessage: string = '';
  user: SocialUser | undefined;
  loggedIn: boolean | undefined = false;

  constructor(
    private authService: AuthService,
    private userService: UserService,
    private GoogleAuthService: SocialAuthService,
    private router: Router,
    private titleService: Title
  ) { }
 


  setTitle(newTitle: string){
    this.titleService.setTitle(newTitle);
  }

  getPageTitle(): string {
    return this.titleService.getTitle();
  }

  // ngOnInit(): void {
  //   // this.GoogleAuthService.authState.subscribe((user) => {
  //   //   this.user = user;
  //   //   this.loggedIn = (user != null);
  //   //   console.log(this.user)
  //   // });

        //descomentar/    
  //   (window as any).onGoogleSignIn = (googleUser: any) => {
  //     const idToken = googleUser.getIdToken().id_token;
  //     this.authService.loginWithGoogle(idToken).subscribe(
  //       (response: any) => {
  //        console.log('Login Successful, token:', response.token);
  //        this.authService.setToken(response.token);
  //         this.router.navigate(['/dashboard']); // Redirige al dashboard después del login exitoso
  //       },
  //       (error: any) => {
  //         console.error('Error en el login:', error);
  //         this.errorMessage = 'Error en el servidor. Por favor, inténtelo de nuevo más tarde.'; // Manejo de errores HTTP
  //       }
  //     )
  //   }
   
  // }


  ngOnInit(): void {
    google.accounts.id.initialize({
      client_id: '236412742841-kb5urirqrtgs16j06m7sifcrgqu8psbf.apps.googleusercontent.com',
      callback: (response: any) => this.handleCredentialResponse(response)
    });
    google.accounts.id.renderButton(
      document.getElementById('buttonDiv'),
      { theme: 'outline', size: 'large' }  // customization attributes
    );
    google.accounts.id.prompt(); // also display the One Tap dialog
  }

  handleCredentialResponse(response: any) {
    this.authService.loginWithGoogle(response.credential).subscribe(
      (response: any) => {
        if(response && response.token) {
          this.authService.setToken(response.token);
          this.router.navigate(['/dashboard']);
        }
        else {
          this.errorMessage = 'Credenciales inválidas'; // Mensaje de error si las credenciales son incorrectas

        }
      },
      (error: any) => {
        console.error('Login failed:', error);
      }
    );
  }


  onSubmit(): void {
    if (this.email && this.password) {
      this.authService.login(this.email, this.password)
        .subscribe(
          (response: any) => {
            if (response && response.token) {
              this.authService.setToken(response.token); // Guarda el token utilizando AuthService
              this.router.navigate(['/dashboard']); // Redirige al dashboard después del login exitoso
            } else {
              this.errorMessage = 'Credenciales inválidas'; // Mensaje de error si las credenciales son incorrectas
            }
          },
          (error) => {
            console.error('Error en el login:', error);
            this.errorMessage = 'Error en el servidor. Por favor, inténtelo de nuevo más tarde.'; // Manejo de errores HTTP
          }
        );
    } else {
      this.errorMessage = 'Por favor, ingrese su correo electrónico y contraseña.';
    }
  }

  // signInWithGoogle():void {
  //   this.GoogleSerive.signIn(GoogleLoginProvider.PROVIDER_ID)
  //    .then((user) => {
  //       console.log('Google Sign-in success', user);
  //       this.userService.createUser(user.email, user.name, user.id)
  //        .subscribe(
  //           (response: any) => {
  //             console.log('Usuario creado con éxito:', response);
  //             this.authService.setToken(response.token); // Guarda el token utilizando AuthService
  //             this.router.navigate(['/dashboard']); // Redirige al dashboard después del login exitoso
  //           },
  //           (error: any) => {
  //             console.error('Error en el registro:', error);
  //             this.errorMessage = 'Error en el servidor. Por favor, inténtelo de nuevo más tarde.'; // Manejo de errores HTTP
  //           }
  //         );
  //     })
  //    .catch((error) => console.error('Google Sign-in errror', error));
  // }

  
  // signInWithGoogle(): void {
  //   this.GoogleAuthService.signIn(GoogleLoginProvider.PROVIDER_ID).catch((error) => {
  //     console.error('Google Sign-in error', error);
  //   });
  // }


}
<script src="https://accounts.google.com/gsi/client" async></script>


<div class="wrapper">
  <div class="inner">
    <img class="image-1" src="./../assets/imagenes/img.png" alt="Image 1" />

    <form (ngSubmit)="onSubmit()" method="post">
      <h3>Iniciar sesión</h3>

      <div class="form-holder">
        <span class="lnr lnr-user"></span>
        <input
          type="text"
          class="form-control"
          [(ngModel)]="email"
          id="email"
          name="email"
          placeholder="Correo"
          required
        />
      </div>

      <div class="form-holder">
        <span class="lnr lnr-lock"></span>
        <input
          type="password"
          class="form-control"
          [(ngModel)]="password"
          id="password"
          name="password"
          placeholder="Contraseña"
          required
        />
      </div>
      <br />
      <div *ngIf="errorMessage" class="error-message">{{ errorMessage }}</div>
      <br />
      <button type="submit">Enviar</button>

      <br /><br />

      <div>
        <a routerLink="/adduser">
          <p>¿Aún no estás registrado?</p>
        </a>
        <a routerLink="/loginadmin">
          <p>¿Eres el admin?</p>
        </a>
      </div>

      <br />

      <br /><br />

          <!-- login.component.html -->
          <div id="buttonDiv"></div>

          <!-- <div
            id="g_id_onload"
            data-client_id="236412742841-kb5urirqrtgs16j06m7sifcrgqu8psbf.apps.googleusercontent.com"
            data-context="signup"
            data-ux_mode="popup"
            
            data-auto_prompt="false"
          ></div>

          <div
            class="g_id_signin"
            data-type="standard"
            data-shape="pill"
            data-theme="filled_blue"
            data-text="signin_with"
            data-size="large"
            data-logo_alignment="left"
          ></div> -->
    </form>

    <img src="./../assets/imagenes/image-2.png" alt="Image 2" class="image-2" />
  </div>
</div>

// caninfe/src/components/login.jsx
import { useState, useEffect } from "react";
import { jwtDecode } from "jwt-decode";
import "../assets/css/login.css";
import "../assets/css/icons.css";
import axios from "axios";
import logo from "../assets/images/image-2.png";
import mujer from "../assets/images/img.png";
// import { useHistory } from "react-router-dom";
import adminlogin from "../components/admin/login";

import adduser from "./adduser";

function Login() {
  const [correo, setCorreo] = useState();
  const [password, setPassword] = useState("");
  const [error, setError] = useState(null);
  const [loading, setLoading] = useState(false);
  const [loggedIn, setLoggedIn] = useState(false);

  function handleCallBackResponse(response) {
    console.log("Encoded JWT ID token: " + response.credential);
    var userObject = jwtDecode(response.credential);
    console.log(userObject);
    setCorreo(userObject.email);
    setLoggedIn(true); // Set isLoggedIn to true on successful login
    window.localStorage.setItem("user", userObject.email);
    document.getElementById("signInDiv").hidden = true;
    window.location.href = "/dashboard";

    var user_email = window.localStorage.getItem(correo);
    console.log(user_email);
  }

  useEffect(() => {
    /*global google */
    document.title = "Login";
    google.accounts.id.initialize({
      client_id:
        "412195763180-f6p9e6o3jqktud93kl5jokejiep5kc8l.apps.googleusercontent.com",
      callback: handleCallBackResponse,
    });

    google.accounts.id.renderButton(document.getElementById("signInDiv"), {
      theme: "outline",
      size: "large",
    });

    google.accounts.id.prompt();
  });

  // Login Function
  function handleSubmit(event) {
    event.preventDefault();

    axios
      .post("http://127.0.0.1:5000/login", { correo, password })
      .then((res) => {
        console.log(res.data);

        setLoading(false);

        if (res.data === "Usuario encontrado") {
          // Corregido el typo de "Usuaro encontrado"
          setLoggedIn(true);
          localStorage.setItem("user", correo);
          window.location.href = "/dashboard";
        } else {
          setError(
            "Error en inicio de sesión. Por favor, verifica tus credenciales."
          );
        }
      })
      .catch((err) => {
        console.error("Error en inicio de sesión:", err);
        setError("Error en inicio de sesión. Por favor, intenta nuevamente.");
        setLoading(false);
      });
  }

  // Outh With GitHub

  function handleGithubLogin() {
    // Redirige al usuario a la página de autorización de GitHub
    window.location.href =
      "https://github.com/login/oauth/authorize?client_id=e3339b26e407afc5d80e&redirect_uri=http://localhost:3000/callback";
  }

  return (
    <>
      <body>
        <div className="wrapper">
          <div className="inner">
            <img
              src={mujer}
              alt=""
              style={{ height: "330px" }}
              className="image-1"
            />

            {/* Form Login */}

            <form
              onSubmit={handleSubmit}
              method="post"
              enctype="multipart/form-data"
            >
              <h3>Iniciar sesion</h3>
              <br />
              <div className="form-holder">
                <span className="lnr lnr-user"></span>
                <input
                  type="text"
                  className="form-control"
                  placeholder="Correo"
                  onChange={(e) => setCorreo(e.target.value)}
                  required
                />
              </div>

              <div className="form-holder">
                <span className="lnr lnr-lock"></span>
                <input
                  type="password"
                  className="form-control"
                  id="password"
                  placeholder="Contraseña"
                  value={password}
                  onChange={(e) => setPassword(e.target.value)}
                  required
                />
              </div>
              {error && <p style={{ color: "red" }}>{error}</p>}
              <button type="submit" disabled={loading}>
                {loading ? "Cargando..." : "Iniciar Sesión"}
              </button>

              <div>
                <br />
                <center>
                  <a href="/adduser">
                    <p>Aún no estás registrado?</p>
                  </a>
                </center>
                <center>
                  <a href="/loginadmin">
                    <p>Eres el admin?</p>
                  </a>
                </center>
              </div>
              <br />
              <center>
                <div id="signInDiv"></div>
                <br></br>
                <button onClick={handleGithubLogin}>
                  Iniciar sesión con GitHub
                </button>
              </center>
            </form>
            <img src={logo} alt="" className="image-2" />
          </div>
        </div>
      </body>
    </>
  );
}

export default Login;
