// caninfe/src/components/adduser.jsx
/* eslint-disable no-unused-vars */
import React, { useState, useEffect } from "react";
import "../assets/css/login.css";
import login from "./login";
import axios from "axios";
import planta from "../assets/images/image-2.png";
import mujer from "../assets/images/img.png";

function Adduser() {
  const [passwordMatchMessage, setPasswordMatchMessage] = useState("");
  const [passwordStrengthMessage, setPasswordStrengthMessage] = useState("");
  const [passwordMatchMessageColor, setPasswordMatchMessageColor] =
    useState("");
  const [passwordStrengthMessageColor, setPasswordStrengthMessageColor] =
    useState("");

  const [correo, setCorreo] = useState({});
  const [password, setPassword] = useState("");
  const [apellido, setApellido] = useState("");
  const [celular, setCelular] = useState("");
  const [identificacion, setIdentificacion] = useState("");
  const [edad, setEdad] = useState("");
  const [peso, setPeso] = useState("");
  const [nombre, setNombre] = useState("");
  const [tipo_documento, setTipo_documento] = useState("");
  const [loading, setLoading] = useState(false);
  const [loggedIn, setLoggedIn] = useState(false);
  const [error, setError] = useState(null);
  const [horaUser, setHoraUser] = useState("");
  const [errorMessage, setErrorMessage] = useState("");


  // Función para validar la fortaleza de la contraseña
  function validatePasswordStrength(password) {
    const hasNumber = /\d/.test(password);
    const hasSpecialChar = /[!@#$%^&*(),.?":{}|<>]/.test(password);
    return hasNumber && hasSpecialChar;
  }

  function handleSubmit(event) {
    event.preventDefault();
    // const horauser = new Date();
    // const fecha = horauser.toISOString().slice(0, 19).replace("T", " ");

    const horauser = new Date();
    const horaColombiana = new Date(horauser.getTime() - (5 * 60 * 60 * 1000)); // Restar 5 horas en milisegundos
    const fecha = horaColombiana.toISOString().slice(0, 19).replace("T", " ");

    axios
      .post("http://127.0.0.1:5000/adduser", {
        nombre,
        apellido,
        tipo_documento,
        celular,
        identificacion,
        edad,
        peso,
        correo,
        password,
        fecha,
      })
      .then((res) => {
        console.log(res.data);
        setLoading(false);
        setLoggedIn(true);
      })
      .catch((err) => {
        console.error("Error en inicio de sesión:", err);
        setError(
          "Error en inicio de sesión. Por favor, verifica tus credenciales."
        );
        setLoading(false);
      });

    if (loggedIn) {
      window.location.href = "/dashboard";
    }
  }

  // Función para manejar el evento onBlur en el campo de confirmación de contraseña
  function handleConfirmPasswordBlur(event) {
    const { value } = event.target;
    const password = document.getElementById("password").value;

    if (password === value) {
      setPasswordMatchMessage("Las contraseñas coinciden");
      setPasswordMatchMessageColor("green");
    } else {
      setPasswordMatchMessage("Las contraseñas no coinciden");
      setPasswordMatchMessageColor("red");
    }

    if (validatePasswordStrength(password)) {
      setPasswordStrengthMessage("La contraseña es fuerte");
      setPasswordStrengthMessageColor("green");
    } else {
      setPasswordStrengthMessage(
        "La contraseña debe contener números y caracteres especiales"
      );
      setPasswordStrengthMessageColor("red");
    }
  }

  useEffect(() => {
    document.title = "Register";
  }, []);

  return (
    <>
      <title>Sign Up</title>
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />

      <div className="wrapper">
        <div className="inner">
          <img src={mujer} alt="" className="image-1" />

          <form onSubmit={handleSubmit}>
            <h3>Regístrese</h3>

            <div className="form-holder">
              <span className="lnr lnr-user"></span>
              <input
                type="text"
                className="form-control"
                placeholder="nombre"
                name="nombre"
                onChange={(e) => setNombre(e.target.value)}
                required
              />
            </div>

            <div className="form-holder">
              <span className="lnr lnr-users"></span>
              <input
                type="text"
                className="form-control"
                placeholder="apellido"
                name="apellido"
                id="apellido"
                onChange={(e) => setApellido(e.target.value)}
                required
              />
            </div>

            <div className="form-holder">
              <span className="lnr lnr-indent-decrease"></span>
              <select
                name="tipo_documento"
                id="tipo_documento"
                onChange={(e) => setTipo_documento(e.target.value)}
                style={{
                  marginLeft: "50px",
                  borderLeft: "var(--size) solid transparent",
                  borderRight: "var(--size) solid transparent",
                  borderTop: "var(--size) solid black",
                }}
              >
                <option value="CC">Cedula de Ciudadania</option>
                <option value="TI">Tarjeta de Identidad</option>
              </select>
            </div>

            <div className="form-holder">
              <span className="lnr lnr-phone"></span>
              <input
                type="text"
                className="form-control"
                placeholder="Phone Number"
                name="celular"
                id="celular"
                onChange={(e) => setCelular(e.target.value)}
              />
            </div>

            <div className="form-holder">
              <span className="lnr lnr-file-add"></span>
              <input
                type="text"
                className="form-control"
                placeholder="identificacion"
                name="identificacion"
                id="identificacion"
                onChange={(e) => setIdentificacion(e.target.value)}
              />
            </div>

            <div className="form-holder">
              <span className="lnr lnr-smile"></span>
              <input
                type="text"
                className="form-control"
                placeholder="Edad"
                name="edad"
                id="edad"
                onChange={(e) => setEdad(e.target.value)}
              />
            </div>

            <div className="form-holder">
              <span className="lnr lnr-heart"></span>
              <input
                type="text"
                className="form-control"
                placeholder="Peso"
                name="peso"
                id="peso"
                onChange={(e) => setPeso(e.target.value)}
              />
            </div>

            <div className="form-holder">
              <span className="lnr lnr-envelope"></span>
              <input
                type="email"
                className="form-control"
                placeholder="Correo"
                name="correo"
                id="correo"
                onChange={(e) => setCorreo(e.target.value)}
                required
              />
            </div>

            <div className="form-holder">
              <span className="lnr lnr-lock"></span>
              <input
                type="password"
                className="form-control"
                placeholder="Contraseña"
                id="password"
                name="password"
                onChange={(e) => setPassword(e.target.value)}
                required
              />
            </div>

            <div className="form-holder">
              <span className="lnr lnr-lock"></span>
              <input
                type="password"
                className="form-control"
                placeholder="Confirma Contraseña"
                id="confirmPassword"
                onBlur={handleConfirmPasswordBlur}
                required
              />
            </div>

            <span
              id="passwordMatchMessage"
              style={{ color: passwordMatchMessageColor }}
            >
              {passwordMatchMessage}
            </span>
            <br />
            <span
              id="passwordStrengthMessage"
              style={{ color: passwordStrengthMessageColor }}
            >
              {passwordStrengthMessage}
            </span>

            <input type="submit" value="submit" />

            <div>
              <br />
              <p>Est&aacute;s registrada?</p>
              <a href="/login/" target="_blank">
                <span>Sí</span>
              </a>
            </div>
          </form>
          {errorMessage && <p>{errorMessage}</p>}

          <img src={planta} alt="" className="image-2" />
        </div>
      </div>
    </>
  );
}

export default Adduser;

// canAi/src/app/components/patients/adduser/adduser.component.ts
import { Component, OnInit } from '@angular/core';
import { UserService } from '../../../services/user.service';
import { AuthService } from '../../../services/auth.service';
import { Router } from '@angular/router';
import { FormGroup, FormBuilder, Validators } from '@angular/forms';


@Component({
  selector: 'app-adduser',
  templateUrl: './adduser.component.html',
  styleUrl: '../../../../assets/css/login.css'
})
export class AdduserComponent  implements OnInit{

  addUserForm: FormGroup;
  errorMessage: string = '';



  constructor(
    private fb: FormBuilder,
    private authService: AuthService,
    private router: Router
  ){
    this.addUserForm = this.fb.group({
      nombre: ['', Validators.required],
      apellido: [''],
      tipo_documento: [''],
      celular: ['', Validators.required],
      identificacion: [''],
      edad: [''],
      peso: [''],
      correo: ['', [Validators.required, Validators.email]],
      password: ['', Validators.required],
      confirmPassword: ['']
    }, { validator: this.passwordMatchValidator });
  }

  
    ngOnInit(): void {}
  
    passwordMatchValidator(formGroup: FormGroup) {
      const password = formGroup.get('password')?.value;
      const confirmPassword = formGroup.get('confirmPassword')?.value;
      if (password !== confirmPassword) {
        formGroup.get('confirmPassword')?.setErrors({ passwordMismatch: true });
      } else {
        formGroup.get('confirmPassword')?.setErrors(null);
      }
      return null;
    }

    onSubmit(): void {
      if (this.addUserForm.valid) {
        const { nombre, apellido, tipo_documento, celular, identificacion, edad, peso, correo, password, id_role, estado } = this.addUserForm.value;
        this.authService.addUser(
          nombre,
          apellido,
          tipo_documento,
          celular,
          identificacion,
          correo,
          edad,
          peso,
          password,
          id_role,
          estado
        ).subscribe(
          (response: any) => {
            if (response && response.token) {
              this.authService.setToken(response.token); // Guarda el token utilizando AuthService
              this.router.navigate(['/dashboard']); // Redirige al dashboard después del registro exitoso
            } else {
              this.errorMessage = 'Error al Registrarse!';
            }
          },
          (error) => {
            console.error('Error en el login:', error);
            this.errorMessage = 'Error en el servidor. Por favor, inténtelo de nuevo más tarde.'; // Manejo de errores HTTP
          }
        );
      } else {
        this.errorMessage = 'Por favor, complete todos los campos requeridos.';
      }
    }
  }
<!--
<div class="wrapper">
  <link
    rel="stylesheet"
    href="https://cdn.linearicons.com/free/1.0.0/icon-font.min.css"
  />
  <div class="inner">
    <img src="./../assets/imagenes/img.png" alt="" class="image-1" />

    <form (ngSubmit)="onSubmit()">
      <h3>Regístrese</h3>

      <div class="form-holder">
        <span class="lnr lnr-user"></span>
        <input
          type="text"
          class="form-control"
          [(ngModel)]="nombre"
          placeholder="nombre"
          name="nombre"

          required
        />
      </div>

      <div class="form-holder">
        <span class="lnr lnr-users"></span>
        <input
          type="text"
          class="form-control"
          [(ngModel)]="apellido"
          placeholder="apellido"
          name="apellido"
          id="apellido"
        />
      </div>

      <div class="form-holder">
        <span class="lnr lnr-indent-decrease"></span>
        <select name="tipo_documento" id="tipo_documento" class="form-control" [(ngModel)] ="tipo_documento">
           <option value="CC">Cedula de Ciudadania</option>
          <option value="TI">Tarjeta de Identidad</option>
          
        </select>
      </div>

      <div class="form-holder">
        <span class="lnr lnr-phone-handset"></span>
        <input
          type="number"
          class="form-control"
          [(ngModel)] ="phone_number"
          placeholder="Phone Number"
          name="celular"
          id="celular"
        />
      </div>

      <div class="form-holder">
        <span class="lnr lnr-file-add"></span>
        <input
          type="number"
          class="form-control"
          [(ngModel)]="identification"
          placeholder=" N&uacute;mero de Identificacion"
          name="identificacion"
          id="identificacion"
        />
      </div>

      <div class="form-holder">
        <span class="lnr lnr-smile"></span>
        <input
          type="number"
          class="form-control"
          [(ngModel)] ="edad"
          placeholder="Edad"
          name="edad"
          id="edad"
        />
      </div>

      <div class="form-holder">
        <span class="lnr lnr-heart"></span>
        <input
          type="nunber"
          class="form-control"
          [(ngModel)] ="peso"
          placeholder="Peso"
          name="peso"
          id="peso"
        />
      </div>

      <div class="form-holder">
        <span class="lnr lnr-envelope"></span>
        <input
          type="email"
          class="form-control"
          placeholder="Correo"
          [(ngModel)] ="correo"
          name="correo"
          id="correo"
          required
        />
      </div>

      <div class="form-holder">
        <span class="lnr lnr-lock"></span>
        <input
          type="password"
          class="form-control"
          [(ngModel)] ="password"
          placeholder="Contraseña"
          id="password"
          name="password"
          required
        />
      </div>

      <div class="form-holder">
        <span class="lnr lnr-lock"></span>
        <input
          type="password"
          class="form-control"
          placeholder="Confirma Contraseña"
          id="confirmPassword"
          required
        />
      </div>

    

      <button type="submit">Send</button>

      <div>
        <br />
        <p>¿Ya estás registrado?</p>
        <a routerLink="/login">
          <span>Sí</span>
        </a>
      </div>
    </form>

    <img src="./../assets/imagenes/image-2.png" alt="" class="image-2" />
  </div>
-->

<div class="wrapper">
  <link rel="stylesheet" href="https://cdn.linearicons.com/free/1.0.0/icon-font.min.css" />
  <div class="inner">
    <img src="./../assets/imagenes/img.png" alt="" class="image-1" />

    <form [formGroup]="addUserForm" (ngSubmit)="onSubmit()">
      <h3>Regístrese</h3>

      <div class="form-holder">
        <span class="lnr lnr-user"></span>
        <input
          type="text"
          class="form-control"
          formControlName="nombre"
          placeholder="nombre"
        />
      </div>

      <div class="form-holder">
        <span class="lnr lnr-users"></span>
        <input
          type="text"
          class="form-control"
          formControlName="apellido"
          placeholder="apellido"
        />
      </div>

      <div class="form-holder">
        <span class="lnr lnr-indent-decrease"></span>
        <select formControlName="tipo_documento" class="form-control">
          <option value="CC">Cédula de Ciudadanía</option>
          <option value="TI">Tarjeta de Identidad</option>
        </select>
      </div>

      <div class="form-holder">
        <span class="lnr lnr-phone-handset"></span>
        <input
          type="number"
          class="form-control"
          formControlName="celular"
          placeholder="Phone Number"
        />
      </div>

      <div class="form-holder">
        <span class="lnr lnr-file-add"></span>
        <input
          type="number"
          class="form-control"
          formControlName="identificacion"
          placeholder="Número de Identificación"
        />
      </div>

      <div class="form-holder">
        <span class="lnr lnr-smile"></span>
        <input
          type="number"
          class="form-control"
          formControlName="edad"
          placeholder="Edad"
        />
      </div>

      <div class="form-holder">
        <span class="lnr lnr-heart"></span>
        <input
          type="number"
          class="form-control"
          formControlName="peso"
          placeholder="Peso"
        />
      </div>

      <div class="form-holder">
        <span class="lnr lnr-envelope"></span>
        <input
          type="email"
          class="form-control"
          formControlName="correo"
          placeholder="Correo"
        />
      </div>

      <div class="form-holder">
        <span class="lnr lnr-lock"></span>
        <input
          type="password"
          class="form-control"
          formControlName="password"
          placeholder="Contraseña"
        />
      </div>

      <div class="form-holder">
        <span class="lnr lnr-lock"></span>
        <input
          type="password"
          class="form-control"
          formControlName="confirmPassword"
          placeholder="Confirma Contraseña"
        />
        <div *ngIf="addUserForm.get('confirmPassword')?.hasError('passwordMismatch')">
          Las contraseñas no coinciden
        </div>
      </div>

      <button type="submit" [disabled]="addUserForm.invalid">Send</button>

      <div>
        <br />
        <p>¿Ya estás registrado?</p>
        <a routerLink="/login">
          <span>Sí</span>
        </a>
      </div>
    </form>

    <img src="./../assets/imagenes/image-2.png" alt="" class="image-2" />
  </div>
</div>
